AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cryptocurrency Email and Search History API

Parameters:
  VersionParam:
    Type: String
    Description: Version number from package.json

  SourceEmail:
    Type: String
    Description: Email address verified in SES

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128

Resources:
  SharedLibsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-libs
      Description: Shared utility functions
      ContentUri: layers/sharedLibs
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain

  ### DynamoDB Table ###
  CryptoSearchHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserSearchHistory
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: recordType   
          AttributeType: S
        - AttributeName: timestamp    
          AttributeType: N
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: RecordTypeIndex
          KeySchema:
            - AttributeName: recordType
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  ### Lambda 1 - Email Cryptocurrency Price ###
  EmailCryptoPriceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: EmailCryptoPriceFunction
      CodeUri: services/email-price-service
      Handler: handlers/getPriceAndSendEmail.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: ses:SendEmail
              Resource: "*"
      Environment:
        Variables:
          REGION_PARAM: ap-southeast-2
          TABLE_NAME: UserSearchHistory
          SOURCE_EMAIL: !Ref SourceEmail
          VERSION: !Ref VersionParam
      Layers:
        - !Ref SharedLibsLayer

      Events:
        EmailCryptoAPI:
          Type: Api
          Properties:
            Path: /price
            Method: POST
    Metadata:
      BuildMethod: nodejs18.x

  ### Lambda 2 - Search History ###
  SearchHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SearchHistoryFunction
      CodeUri: services/history-service
      Handler: handlers/getHistory.handler
      Policies:
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: UserSearchHistory
      Layers:
        - !Ref SharedLibsLayer

      Events:
        SearchHistoryAPI:
          Type: Api
          Properties:
            Path: /history
            Method: GET

Outputs:
  EmailCryptoAPIEndpoint:
    Description: "POST endpoint to request cryptocurrency price by email"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/price"

  SearchHistoryAPIEndpoint:
    Description: "GET endpoint to retrieve search history"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/history"
